# Список сервисов которые нужно создать
services:
  # Сервис 1: Backend FastAPI
  - type: web                    # Тип: веб-сервер (будет доступен по URL)
    name: nutricoach-backend     # Имя сервиса
    env: python                  # Язык программирования
    region: oregon               # Регион (ближайший к Европе)
    plan: free                   # Бесплатный план
    
    # Команда для установки зависимостей
    buildCommand: "cd miniapp/backend && pip install -r requirements.txt"
    
    # Команда для запуска приложения
    startCommand: "cd miniapp/backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    
    # Переменные окружения
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      
      # Эти переменные нужно будет ввести вручную (sync: false = не из файла)
      - key: POSTGRES_DSN
        sync: false
      
      - key: OPENROUTER_API_KEY
        sync: false
      
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      
      - key: APP_TITLE
        value: NutriCoach
      
      - key: APP_REFERER
        sync: false

  # Сервис 2: Telegram Bot
  - type: worker                 # Тип: фоновый процесс (без URL)
    name: nutricoach-bot
    env: python
    region: oregon
    plan: free
    
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m bot.final"
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      
      - key: POSTGRES_DSN
        sync: false
      
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      
      - key: MINI_APP_URL
        sync: false
      
      - key: PAYMENT_PROVIDER_TOKEN
        value: ""
      
      - key: TRIAL_HOURS
        value: "24"
      
      - key: ADMIN_USERNAME
        sync: false